// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: glob/v1/glob.proto

package globv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectOp int32

const (
	ObjectOp_OBJECT_OP_UNSPECIFIED ObjectOp = 0
	ObjectOp_OBJECT_OP_ADD         ObjectOp = 1
	ObjectOp_OBJECT_OP_REMOVE      ObjectOp = 2
	ObjectOp_OBJECT_OP_CHANGE      ObjectOp = 3
	ObjectOp_OBJECT_OP_RENAME      ObjectOp = 4
)

// Enum value maps for ObjectOp.
var (
	ObjectOp_name = map[int32]string{
		0: "OBJECT_OP_UNSPECIFIED",
		1: "OBJECT_OP_ADD",
		2: "OBJECT_OP_REMOVE",
		3: "OBJECT_OP_CHANGE",
		4: "OBJECT_OP_RENAME",
	}
	ObjectOp_value = map[string]int32{
		"OBJECT_OP_UNSPECIFIED": 0,
		"OBJECT_OP_ADD":         1,
		"OBJECT_OP_REMOVE":      2,
		"OBJECT_OP_CHANGE":      3,
		"OBJECT_OP_RENAME":      4,
	}
)

func (x ObjectOp) Enum() *ObjectOp {
	p := new(ObjectOp)
	*p = x
	return p
}

func (x ObjectOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectOp) Descriptor() protoreflect.EnumDescriptor {
	return file_glob_v1_glob_proto_enumTypes[0].Descriptor()
}

func (ObjectOp) Type() protoreflect.EnumType {
	return &file_glob_v1_glob_proto_enumTypes[0]
}

func (x ObjectOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectOp.Descriptor instead.
func (ObjectOp) EnumDescriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{0}
}

// Object is the path, hashes, and data of an object.
type Object struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ObjectStatus is the path and hashes of an object.
	ObjectStatus *ObjectStatus `protobuf:"bytes,1,opt,name=object_status,json=objectStatus,proto3" json:"object_status,omitempty"`
	// Data is a slice of byte slices which correspond to the hash of the status at the same index.
	Data          [][]byte `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_glob_v1_glob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{0}
}

func (x *Object) GetObjectStatus() *ObjectStatus {
	if x != nil {
		return x.ObjectStatus
	}
	return nil
}

func (x *Object) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ObjectStatus is the path and hashes of an object.
type ObjectStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path is the filesystem target object
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Hash is a slice of hashes for the given path.
	Hash          [][]byte `protobuf:"bytes,2,rep,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectStatus) Reset() {
	*x = ObjectStatus{}
	mi := &file_glob_v1_glob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectStatus) ProtoMessage() {}

func (x *ObjectStatus) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectStatus.ProtoReflect.Descriptor instead.
func (*ObjectStatus) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectStatus) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ObjectStatus) GetHash() [][]byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Target is the directory on disk to replicate.
type Target struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id             []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdateTime string                 `protobuf:"bytes,3,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	Object         []*Object              `protobuf:"bytes,4,rep,name=object,proto3" json:"object,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_glob_v1_glob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{2}
}

func (x *Target) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Target) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Target) GetLastUpdateTime() string {
	if x != nil {
		return x.LastUpdateTime
	}
	return ""
}

func (x *Target) GetObject() []*Object {
	if x != nil {
		return x.Object
	}
	return nil
}

type TargetStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LastUpdateTime string                 `protobuf:"bytes,2,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	ObjectStatus   []*ObjectStatus        `protobuf:"bytes,3,rep,name=object_status,json=objectStatus,proto3" json:"object_status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TargetStatus) Reset() {
	*x = TargetStatus{}
	mi := &file_glob_v1_glob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetStatus) ProtoMessage() {}

func (x *TargetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetStatus.ProtoReflect.Descriptor instead.
func (*TargetStatus) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{3}
}

func (x *TargetStatus) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TargetStatus) GetLastUpdateTime() string {
	if x != nil {
		return x.LastUpdateTime
	}
	return ""
}

func (x *TargetStatus) GetObjectStatus() []*ObjectStatus {
	if x != nil {
		return x.ObjectStatus
	}
	return nil
}

// Replica is a peer host with which to sync data
type Replica struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       []byte                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replica) Reset() {
	*x = Replica{}
	mi := &file_glob_v1_glob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replica) ProtoMessage() {}

func (x *Replica) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replica.ProtoReflect.Descriptor instead.
func (*Replica) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{4}
}

func (x *Replica) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Replica) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Replica) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

// ObjectNotification is a notification of an object change.
type ObjectNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      []byte                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Op            ObjectOp               `protobuf:"varint,3,opt,name=op,proto3,enum=glob.v1.ObjectOp" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectNotification) Reset() {
	*x = ObjectNotification{}
	mi := &file_glob_v1_glob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectNotification) ProtoMessage() {}

func (x *ObjectNotification) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectNotification.ProtoReflect.Descriptor instead.
func (*ObjectNotification) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{5}
}

func (x *ObjectNotification) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *ObjectNotification) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ObjectNotification) GetOp() ObjectOp {
	if x != nil {
		return x.Op
	}
	return ObjectOp_OBJECT_OP_UNSPECIFIED
}

// HashNotification is a notification of an object hash change.
type HashNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      []byte                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ChunkMeta     *ChunkMeta             `protobuf:"bytes,3,opt,name=chunk_meta,json=chunkMeta,proto3" json:"chunk_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashNotification) Reset() {
	*x = HashNotification{}
	mi := &file_glob_v1_glob_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashNotification) ProtoMessage() {}

func (x *HashNotification) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashNotification.ProtoReflect.Descriptor instead.
func (*HashNotification) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{6}
}

func (x *HashNotification) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *HashNotification) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HashNotification) GetChunkMeta() *ChunkMeta {
	if x != nil {
		return x.ChunkMeta
	}
	return nil
}

// ChunkMeta is the chunk metadata for an object.
type ChunkMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ByteWidth     int64                  `protobuf:"varint,1,opt,name=byte_width,json=byteWidth,proto3" json:"byte_width,omitempty"`
	Hashes        [][]byte               `protobuf:"bytes,2,rep,name=hashes,proto3" json:"hashes,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Hash          []byte                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkMeta) Reset() {
	*x = ChunkMeta{}
	mi := &file_glob_v1_glob_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkMeta) ProtoMessage() {}

func (x *ChunkMeta) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkMeta.ProtoReflect.Descriptor instead.
func (*ChunkMeta) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkMeta) GetByteWidth() int64 {
	if x != nil {
		return x.ByteWidth
	}
	return 0
}

func (x *ChunkMeta) GetHashes() [][]byte {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *ChunkMeta) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *ChunkMeta) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// ChunkData is the chunk data for an individual chunk of an object.
type ChunkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_glob_v1_glob_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{8}
}

func (x *ChunkData) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *ChunkData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FetchChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      []byte                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Object        []*Object              `protobuf:"bytes,2,rep,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchChunksRequest) Reset() {
	*x = FetchChunksRequest{}
	mi := &file_glob_v1_glob_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchChunksRequest) ProtoMessage() {}

func (x *FetchChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchChunksRequest.ProtoReflect.Descriptor instead.
func (*FetchChunksRequest) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{9}
}

func (x *FetchChunksRequest) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *FetchChunksRequest) GetObject() []*Object {
	if x != nil {
		return x.Object
	}
	return nil
}

type FetchChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      []byte                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Object        []*Object              `protobuf:"bytes,2,rep,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchChunksResponse) Reset() {
	*x = FetchChunksResponse{}
	mi := &file_glob_v1_glob_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchChunksResponse) ProtoMessage() {}

func (x *FetchChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchChunksResponse.ProtoReflect.Descriptor instead.
func (*FetchChunksResponse) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{10}
}

func (x *FetchChunksResponse) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *FetchChunksResponse) GetObject() []*Object {
	if x != nil {
		return x.Object
	}
	return nil
}

type GetTargetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      []byte                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetStatusRequest) Reset() {
	*x = GetTargetStatusRequest{}
	mi := &file_glob_v1_glob_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetStatusRequest) ProtoMessage() {}

func (x *GetTargetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTargetStatusRequest) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{11}
}

func (x *GetTargetStatusRequest) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

type GetTargetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetStatus  *TargetStatus          `protobuf:"bytes,2,opt,name=target_status,json=targetStatus,proto3" json:"target_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetStatusResponse) Reset() {
	*x = GetTargetStatusResponse{}
	mi := &file_glob_v1_glob_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetStatusResponse) ProtoMessage() {}

func (x *GetTargetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTargetStatusResponse) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{12}
}

func (x *GetTargetStatusResponse) GetTargetStatus() *TargetStatus {
	if x != nil {
		return x.TargetStatus
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      []byte                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_glob_v1_glob_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{13}
}

func (x *SubscribeRequest) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      []byte                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"` // relative to the target root
	Op            ObjectOp               `protobuf:"varint,3,opt,name=op,proto3,enum=glob.v1.ObjectOp" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_glob_v1_glob_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glob_v1_glob_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_glob_v1_glob_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeResponse) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *SubscribeResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SubscribeResponse) GetOp() ObjectOp {
	if x != nil {
		return x.Op
	}
	return ObjectOp_OBJECT_OP_UNSPECIFIED
}

var File_glob_v1_glob_proto protoreflect.FileDescriptor

const file_glob_v1_glob_proto_rawDesc = "" +
	"\n" +
	"\x12glob/v1/glob.proto\x12\aglob.v1\"X\n" +
	"\x06Object\x12:\n" +
	"\robject_status\x18\x01 \x01(\v2\x15.glob.v1.ObjectStatusR\fobjectStatus\x12\x12\n" +
	"\x04data\x18\x03 \x03(\fR\x04data\"6\n" +
	"\fObjectStatus\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04hash\x18\x02 \x03(\fR\x04hash\"\x7f\n" +
	"\x06Target\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12(\n" +
	"\x10last_update_time\x18\x03 \x01(\tR\x0elastUpdateTime\x12'\n" +
	"\x06object\x18\x04 \x03(\v2\x0f.glob.v1.ObjectR\x06object\"\x84\x01\n" +
	"\fTargetStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12(\n" +
	"\x10last_update_time\x18\x02 \x01(\tR\x0elastUpdateTime\x12:\n" +
	"\robject_status\x18\x03 \x03(\v2\x15.glob.v1.ObjectStatusR\fobjectStatus\"P\n" +
	"\aReplica\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\fR\aaddress\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"h\n" +
	"\x12ObjectNotification\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\fR\btargetId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12!\n" +
	"\x02op\x18\x03 \x01(\x0e2\x11.glob.v1.ObjectOpR\x02op\"v\n" +
	"\x10HashNotification\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\fR\btargetId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x121\n" +
	"\n" +
	"chunk_meta\x18\x03 \x01(\v2\x12.glob.v1.ChunkMetaR\tchunkMeta\"w\n" +
	"\tChunkMeta\x12\x1d\n" +
	"\n" +
	"byte_width\x18\x01 \x01(\x03R\tbyteWidth\x12\x16\n" +
	"\x06hashes\x18\x02 \x03(\fR\x06hashes\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\fR\x04hash\"3\n" +
	"\tChunkData\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"Z\n" +
	"\x12FetchChunksRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\fR\btargetId\x12'\n" +
	"\x06object\x18\x02 \x03(\v2\x0f.glob.v1.ObjectR\x06object\"[\n" +
	"\x13FetchChunksResponse\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\fR\btargetId\x12'\n" +
	"\x06object\x18\x02 \x03(\v2\x0f.glob.v1.ObjectR\x06object\"5\n" +
	"\x16GetTargetStatusRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\fR\btargetId\"U\n" +
	"\x17GetTargetStatusResponse\x12:\n" +
	"\rtarget_status\x18\x02 \x01(\v2\x15.glob.v1.TargetStatusR\ftargetStatus\"/\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\fR\btargetId\"g\n" +
	"\x11SubscribeResponse\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\fR\btargetId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12!\n" +
	"\x02op\x18\x03 \x01(\x0e2\x11.glob.v1.ObjectOpR\x02op*z\n" +
	"\bObjectOp\x12\x19\n" +
	"\x15OBJECT_OP_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rOBJECT_OP_ADD\x10\x01\x12\x14\n" +
	"\x10OBJECT_OP_REMOVE\x10\x02\x12\x14\n" +
	"\x10OBJECT_OP_CHANGE\x10\x03\x12\x14\n" +
	"\x10OBJECT_OP_RENAME\x10\x042\xf3\x01\n" +
	"\vSyncService\x12T\n" +
	"\x0fGetTargetStatus\x12\x1f.glob.v1.GetTargetStatusRequest\x1a .glob.v1.GetTargetStatusResponse\x12H\n" +
	"\vFetchChunks\x12\x1b.glob.v1.FetchChunksRequest\x1a\x1c.glob.v1.FetchChunksResponse\x12D\n" +
	"\tSubscribe\x12\x19.glob.v1.SubscribeRequest\x1a\x1a.glob.v1.SubscribeResponse0\x01B\x82\x01\n" +
	"\vcom.glob.v1B\tGlobProtoP\x01Z+github.com/zachfi/glob/proto/glob/v1;globv1\xa2\x02\x03GXX\xaa\x02\aGlob.V1\xca\x02\aGlob\\V1\xe2\x02\x13Glob\\V1\\GPBMetadata\xea\x02\bGlob::V1b\x06proto3"

var (
	file_glob_v1_glob_proto_rawDescOnce sync.Once
	file_glob_v1_glob_proto_rawDescData []byte
)

func file_glob_v1_glob_proto_rawDescGZIP() []byte {
	file_glob_v1_glob_proto_rawDescOnce.Do(func() {
		file_glob_v1_glob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_glob_v1_glob_proto_rawDesc), len(file_glob_v1_glob_proto_rawDesc)))
	})
	return file_glob_v1_glob_proto_rawDescData
}

var file_glob_v1_glob_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_glob_v1_glob_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_glob_v1_glob_proto_goTypes = []any{
	(ObjectOp)(0),                   // 0: glob.v1.ObjectOp
	(*Object)(nil),                  // 1: glob.v1.Object
	(*ObjectStatus)(nil),            // 2: glob.v1.ObjectStatus
	(*Target)(nil),                  // 3: glob.v1.Target
	(*TargetStatus)(nil),            // 4: glob.v1.TargetStatus
	(*Replica)(nil),                 // 5: glob.v1.Replica
	(*ObjectNotification)(nil),      // 6: glob.v1.ObjectNotification
	(*HashNotification)(nil),        // 7: glob.v1.HashNotification
	(*ChunkMeta)(nil),               // 8: glob.v1.ChunkMeta
	(*ChunkData)(nil),               // 9: glob.v1.ChunkData
	(*FetchChunksRequest)(nil),      // 10: glob.v1.FetchChunksRequest
	(*FetchChunksResponse)(nil),     // 11: glob.v1.FetchChunksResponse
	(*GetTargetStatusRequest)(nil),  // 12: glob.v1.GetTargetStatusRequest
	(*GetTargetStatusResponse)(nil), // 13: glob.v1.GetTargetStatusResponse
	(*SubscribeRequest)(nil),        // 14: glob.v1.SubscribeRequest
	(*SubscribeResponse)(nil),       // 15: glob.v1.SubscribeResponse
}
var file_glob_v1_glob_proto_depIdxs = []int32{
	2,  // 0: glob.v1.Object.object_status:type_name -> glob.v1.ObjectStatus
	1,  // 1: glob.v1.Target.object:type_name -> glob.v1.Object
	2,  // 2: glob.v1.TargetStatus.object_status:type_name -> glob.v1.ObjectStatus
	0,  // 3: glob.v1.ObjectNotification.op:type_name -> glob.v1.ObjectOp
	8,  // 4: glob.v1.HashNotification.chunk_meta:type_name -> glob.v1.ChunkMeta
	1,  // 5: glob.v1.FetchChunksRequest.object:type_name -> glob.v1.Object
	1,  // 6: glob.v1.FetchChunksResponse.object:type_name -> glob.v1.Object
	4,  // 7: glob.v1.GetTargetStatusResponse.target_status:type_name -> glob.v1.TargetStatus
	0,  // 8: glob.v1.SubscribeResponse.op:type_name -> glob.v1.ObjectOp
	12, // 9: glob.v1.SyncService.GetTargetStatus:input_type -> glob.v1.GetTargetStatusRequest
	10, // 10: glob.v1.SyncService.FetchChunks:input_type -> glob.v1.FetchChunksRequest
	14, // 11: glob.v1.SyncService.Subscribe:input_type -> glob.v1.SubscribeRequest
	13, // 12: glob.v1.SyncService.GetTargetStatus:output_type -> glob.v1.GetTargetStatusResponse
	11, // 13: glob.v1.SyncService.FetchChunks:output_type -> glob.v1.FetchChunksResponse
	15, // 14: glob.v1.SyncService.Subscribe:output_type -> glob.v1.SubscribeResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_glob_v1_glob_proto_init() }
func file_glob_v1_glob_proto_init() {
	if File_glob_v1_glob_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_glob_v1_glob_proto_rawDesc), len(file_glob_v1_glob_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_glob_v1_glob_proto_goTypes,
		DependencyIndexes: file_glob_v1_glob_proto_depIdxs,
		EnumInfos:         file_glob_v1_glob_proto_enumTypes,
		MessageInfos:      file_glob_v1_glob_proto_msgTypes,
	}.Build()
	File_glob_v1_glob_proto = out.File
	file_glob_v1_glob_proto_goTypes = nil
	file_glob_v1_glob_proto_depIdxs = nil
}
